# Generated by Django 2.2.7 on 2019-12-27 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20191223_1038'), ('core', '0003_auto_20191226_1300'), ('core', '0004_auto_20191226_1400'), ('core', '0005_remove_userfeed_title'), ('core', '0006_auto_20191226_1805'), ('core', '0007_auto_20191226_1808'), ('core', '0008_auto_20191226_1814'), ('core', '0009_auto_20191226_1814'), ('core', '0010_auto_20191226_1909'), ('core', '0011_auto_20191227_1125'), ('core', '0012_remove_profile_followed'), ('core', '0013_profile_followed')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('hobby', models.ManyToManyField(to='core.Hobby')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_profile_posted', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='following', to='core.Followers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='core.Followers'),
        ),
    ]
