# Generated by Django 2.2.7 on 2019-12-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191226_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeed',
            old_name='start_date',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_feed',
        ),
        migrations.AddField(
            model_name='userfeed',
            name='user_profile_posted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
