# Generated by Django 2.2.7 on 2019-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191130_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='ex@mail.com', help_text='Optional.', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='example', help_text='Optional.', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='example', help_text='Optional.', max_length=30),
        ),
    ]
