# Generated by Django 2.2.7 on 2019-12-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userfeed_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(related_name='followed_by', to='core.Followers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='core.Followers'),
        ),
    ]
