# Generated by Django 2.2.7 on 2019-12-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191226_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='core.Followers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='following', to='core.Followers'),
        ),
    ]
