# Generated by Django 2.2.7 on 2019-12-08 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.AddField(
            model_name='hobby',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
