# Generated by Django 2.2.7 on 2019-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191226_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='id_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
