# Generated by Django 2.2.7 on 2019-12-27 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20191226_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='id_followers',
        ),
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
