# Generated by Django 2.2.7 on 2019-12-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby',
            new_name='name',
        ),
    ]
