# Generated by Django 2.2.7 on 2019-12-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='core.Followers'),
        ),
    ]
