# Generated by Django 2.2.7 on 2019-12-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191229_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='user_profile_posted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
