# Generated by Django 2.2.7 on 2020-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200102_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='core.Profile'),
        ),
    ]
