# Generated by Django 2.2.7 on 2020-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_groupchat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='chat_title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
