# Generated by Django 2.2.7 on 2020-01-18 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200115_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
